# Generated by Django 4.2 on 2023-11-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_bigcity_code_alter_bigvillage_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigcity',
            name='Code',
            field=models.IntegerField(default=5932611, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bigvillage',
            name='Code',
            field=models.IntegerField(default=1703629, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='Code',
            field=models.IntegerField(default=5410385, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citypart',
            name='Code',
            field=models.IntegerField(default=9889529, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Code',
            field=models.IntegerField(default=7665630, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peoplebelongvillage',
            name='Code',
            field=models.IntegerField(default=2495914, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='village',
            name='Code',
            field=models.IntegerField(default=2312295, primary_key=True, serialize=False),
        ),
    ]
