# Generated by Django 4.2 on 2023-11-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_bigcity_code_alter_bigvillage_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigcity',
            name='Code',
            field=models.IntegerField(default=5350228, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bigvillage',
            name='Code',
            field=models.IntegerField(default=7918102, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='Code',
            field=models.IntegerField(default=5254964, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citypart',
            name='Code',
            field=models.IntegerField(default=7898536, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Code',
            field=models.IntegerField(default=8276112, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peoplebelongvillage',
            name='Code',
            field=models.IntegerField(default=2997106, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='village',
            name='Code',
            field=models.IntegerField(default=2982295, primary_key=True, serialize=False),
        ),
    ]
