# Generated by Django 4.2 on 2023-11-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_bigcity_code_alter_bigvillage_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigcity',
            name='Code',
            field=models.IntegerField(default=5201413, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bigvillage',
            name='Code',
            field=models.IntegerField(default=5429281, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='Code',
            field=models.IntegerField(default=5715775, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citypart',
            name='Code',
            field=models.IntegerField(default=2551800, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Code',
            field=models.IntegerField(default=4178335, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peoplebelongvillage',
            name='Code',
            field=models.IntegerField(default=2934355, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='village',
            name='Code',
            field=models.IntegerField(default=2590769, primary_key=True, serialize=False),
        ),
    ]
