# Generated by Django 4.2 on 2023-12-12 04:46

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_proper_alter_bigcity_code_alter_bigvillage_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplebelongvillage',
            name='Village',
        ),
        migrations.AddField(
            model_name='peoplebelongvillage',
            name='LocationCode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bigcity',
            name='Code',
            field=models.IntegerField(default=5777763, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bigvillage',
            name='Code',
            field=models.IntegerField(default=7965271, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='Code',
            field=models.IntegerField(default=5679958, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citypart',
            name='Code',
            field=models.IntegerField(default=7669176, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Code',
            field=models.IntegerField(default=7609121, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peoplebelongvillage',
            name='Code',
            field=models.IntegerField(default=2176505, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proper',
            name='Code',
            field=models.IntegerField(default=index.models.randIntAnything, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='village',
            name='Code',
            field=models.IntegerField(default=2338602, primary_key=True, serialize=False),
        ),
    ]
