# Generated by Django 4.2 on 2023-12-12 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_remove_peoplebelongvillage_village_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleBelongLocation',
            fields=[
                ('Code', models.IntegerField(default=2282045, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('Family', models.CharField(max_length=150)),
                ('LocationCode', models.IntegerField(default=0)),
                ('Description', models.TextField(max_length=1500)),
                ('Proper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.proper')),
            ],
        ),
        migrations.AlterField(
            model_name='bigcity',
            name='Code',
            field=models.IntegerField(default=5907078, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bigvillage',
            name='Code',
            field=models.IntegerField(default=7779274, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='Code',
            field=models.IntegerField(default=5283339, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citypart',
            name='Code',
            field=models.IntegerField(default=7914918, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Code',
            field=models.IntegerField(default=7469384, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='village',
            name='Code',
            field=models.IntegerField(default=2189414, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='PeopleBelongVillage',
        ),
    ]
