# Generated by Django 4.2 on 2024-01-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_peoplebelonglocation_alter_bigcity_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('Code', models.IntegerField(default=7176061, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('AccessLevel', models.IntegerField(choices=[(1, 'Main Admin'), (2, 'Trustee'), (3, 'Responsible')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='bigcity',
            name='Code',
            field=models.IntegerField(default=5192737, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bigvillage',
            name='Code',
            field=models.IntegerField(default=7198618, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='Code',
            field=models.IntegerField(default=5432682, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citypart',
            name='Code',
            field=models.IntegerField(default=7384238, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Code',
            field=models.IntegerField(default=7485368, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peoplebelonglocation',
            name='Code',
            field=models.IntegerField(default=2475840, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='village',
            name='Code',
            field=models.IntegerField(default=2259315, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.character'),
        ),
    ]
