# Generated by Django 4.2 on 2024-01-06 15:42

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_apikey_alter_bigcity_code_alter_bigvillage_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='Session',
            field=models.CharField(default=index.models.sesProduction, max_length=200),
        ),
        migrations.AlterField(
            model_name='bigcity',
            name='Code',
            field=models.IntegerField(default=5489825, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bigvillage',
            name='Code',
            field=models.IntegerField(default=7188040, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='Code',
            field=models.IntegerField(default=7871267, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='Code',
            field=models.IntegerField(default=5535696, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citypart',
            name='Code',
            field=models.IntegerField(default=7591828, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Code',
            field=models.IntegerField(default=7797624, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peoplebelonglocation',
            name='Code',
            field=models.IntegerField(default=2974234, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='village',
            name='Code',
            field=models.IntegerField(default=2208478, primary_key=True, serialize=False),
        ),
    ]
