# Generated by Django 4.2 on 2024-01-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_manager_session_alter_bigcity_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='Password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bigcity',
            name='Code',
            field=models.IntegerField(default=5139964, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bigvillage',
            name='Code',
            field=models.IntegerField(default=7129876, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='Code',
            field=models.IntegerField(default=7451284, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='Code',
            field=models.IntegerField(default=5124083, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citypart',
            name='Code',
            field=models.IntegerField(default=7151520, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Code',
            field=models.IntegerField(default=7680266, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peoplebelonglocation',
            name='Code',
            field=models.IntegerField(default=2876014, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='village',
            name='Code',
            field=models.IntegerField(default=2902991, primary_key=True, serialize=False),
        ),
    ]
