# Generated by Django 4.2 on 2024-01-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_bigcity_isdeleted_bigvillage_isdeleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='nPopulation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bigcity',
            name='Code',
            field=models.IntegerField(default=5372700, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bigvillage',
            name='Code',
            field=models.IntegerField(default=7393514, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='Code',
            field=models.IntegerField(default=7545565, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='Code',
            field=models.IntegerField(default=5876737, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citypart',
            name='Code',
            field=models.IntegerField(default=7901423, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Code',
            field=models.IntegerField(default=7147882, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peoplebelonglocation',
            name='Code',
            field=models.IntegerField(default=2406146, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='village',
            name='Code',
            field=models.IntegerField(default=2448982, primary_key=True, serialize=False),
        ),
    ]
