# Generated by Django 4.2 on 2024-01-10 05:16

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_village_npopulation_alter_bigcity_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedundantInformation',
            fields=[
                ('Code', models.IntegerField(default=7459556, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('ForLocation', models.IntegerField(choices=[(1, 'Big City'), (2, 'City'), (3, 'Village')], default=1)),
                ('RegisterTime', django_jalali.db.models.jDateTimeField(default=index.models.currentDateTime)),
            ],
        ),
        migrations.AddField(
            model_name='bigcity',
            name='type',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='bigvillage',
            name='type',
            field=models.IntegerField(default=4, editable=False),
        ),
        migrations.AddField(
            model_name='city',
            name='type',
            field=models.IntegerField(default=2, editable=False),
        ),
        migrations.AddField(
            model_name='citypart',
            name='type',
            field=models.IntegerField(default=3, editable=False),
        ),
        migrations.AddField(
            model_name='village',
            name='type',
            field=models.IntegerField(default=5, editable=False),
        ),
        migrations.AlterField(
            model_name='bigcity',
            name='Code',
            field=models.IntegerField(default=5503844, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bigvillage',
            name='Code',
            field=models.IntegerField(default=7588136, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='Code',
            field=models.IntegerField(default=7889230, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='Code',
            field=models.IntegerField(default=5310323, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citypart',
            name='Code',
            field=models.IntegerField(default=7173075, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Code',
            field=models.IntegerField(default=7151993, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peoplebelonglocation',
            name='Code',
            field=models.IntegerField(default=2159039, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='village',
            name='Code',
            field=models.IntegerField(default=2631132, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ReInformationValue',
            fields=[
                ('Code', models.IntegerField(default=7448868, primary_key=True, serialize=False)),
                ('LocationCode', models.IntegerField(default=0)),
                ('Value', models.CharField(max_length=500)),
                ('RegisterTime', django_jalali.db.models.jDateTimeField(default=index.models.currentDateTime)),
                ('RedundantInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.redundantinformation')),
            ],
        ),
    ]
