# Generated by Django 4.2 on 2024-01-10 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_redundantinformation_bigcity_type_bigvillage_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='BigVillage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='index.bigvillage'),
        ),
        migrations.AlterField(
            model_name='bigcity',
            name='Code',
            field=models.IntegerField(default=5878105, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bigvillage',
            name='Code',
            field=models.IntegerField(default=7253909, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='Code',
            field=models.IntegerField(default=7492944, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='Code',
            field=models.IntegerField(default=5221698, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citypart',
            name='Code',
            field=models.IntegerField(default=7686093, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Code',
            field=models.IntegerField(default=7434237, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peoplebelonglocation',
            name='Code',
            field=models.IntegerField(default=2141224, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='redundantinformation',
            name='Code',
            field=models.IntegerField(default=7145869, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reinformationvalue',
            name='Code',
            field=models.IntegerField(default=7389433, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='village',
            name='Code',
            field=models.IntegerField(default=2143751, primary_key=True, serialize=False),
        ),
    ]
