# Generated by Django 4.2 on 2024-01-10 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_village_bigvillage_alter_bigcity_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigcity',
            name='Code',
            field=models.IntegerField(default=5433933, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bigvillage',
            name='Code',
            field=models.IntegerField(default=7139447, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='Code',
            field=models.IntegerField(default=7155989, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='Code',
            field=models.IntegerField(default=5477004, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citypart',
            name='Code',
            field=models.IntegerField(default=7971775, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Code',
            field=models.IntegerField(default=7895495, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peoplebelonglocation',
            name='Code',
            field=models.IntegerField(default=2614742, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='redundantinformation',
            name='Code',
            field=models.IntegerField(default=7180991, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reinformationvalue',
            name='Code',
            field=models.IntegerField(default=7432873, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='village',
            name='BigVillage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.bigvillage'),
        ),
        migrations.AlterField(
            model_name='village',
            name='Code',
            field=models.IntegerField(default=2279801, primary_key=True, serialize=False),
        ),
    ]
