# Generated by Django 4.2 on 2024-01-15 08:39

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_alter_bigcity_code_alter_bigvillage_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigcity',
            name='Code',
            field=models.IntegerField(default=index.models.randIntCity, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bigvillage',
            name='Code',
            field=models.IntegerField(default=index.models.randIntAnything, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='Code',
            field=models.IntegerField(default=index.models.randIntAnything, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='Code',
            field=models.IntegerField(default=index.models.randIntCity, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citypart',
            name='Code',
            field=models.IntegerField(default=index.models.randIntAnything, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Code',
            field=models.IntegerField(default=index.models.randIntAnything, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peoplebelonglocation',
            name='Code',
            field=models.IntegerField(default=index.models.randIntVillage, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='redundantinformation',
            name='Code',
            field=models.IntegerField(default=index.models.randIntAnything, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='redundantinformation',
            name='ForLocation',
            field=models.IntegerField(choices=[(1, 'Big City'), (2, 'City'), (3, 'City Part'), (4, 'Big Village'), (5, 'Village')], default=1),
        ),
        migrations.AlterField(
            model_name='reinformationvalue',
            name='Code',
            field=models.IntegerField(default=index.models.randIntAnything, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='village',
            name='Code',
            field=models.IntegerField(default=index.models.randIntVillage, primary_key=True, serialize=False),
        ),
    ]
