# Generated by Django 4.2 on 2024-01-20 22:29

from django.db import migrations, models
import django_jalali.db.models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_section_accesscharacter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportPropertyList',
            fields=[
                ('Code', models.IntegerField(default=index.models.randIntAnything, primary_key=True, serialize=False)),
                ('List', models.CharField(max_length=500)),
                ('RegisterTime', django_jalali.db.models.jDateTimeField(default=index.models.currentDateTime)),
            ],
        ),
    ]
