# Generated by Django 4.2 on 2024-01-22 17:36

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_exportpropertylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('Code', models.IntegerField(default=index.models.randIntAnything, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('RegisterTime', django_jalali.db.models.jDateTimeField(default=index.models.currentDateTime)),
            ],
        ),
        migrations.AddField(
            model_name='answertoproperty',
            name='EditTime',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peoplebelonglocation',
            name='AttachmentFile',
            field=models.FileField(blank=True, null=True, upload_to=index.models.uploadToAttachmentToPeople),
        ),
        migrations.AddField(
            model_name='peoplebelonglocation',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertybelongplace',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redundantinformation',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SolutionBelongToProperty',
            fields=[
                ('Code', models.IntegerField(default=index.models.randIntAnything, primary_key=True, serialize=False)),
                ('Content', models.TextField(max_length=2000)),
                ('RegisterTime', django_jalali.db.models.jDateTimeField(default=index.models.currentDateTime)),
                ('Organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.organization')),
                ('PropertyBelongPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.propertybelongplace')),
            ],
        ),
    ]
