# Generated by Django 4.2 on 2024-01-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_organization_answertoproperty_edittime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='ForUse',
            field=models.IntegerField(default=1),
        ),
    ]
