# Generated by Django 4.2 on 2024-01-28 09:01

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_apikey_foruse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='ForUse',
            field=models.IntegerField(choices=[(1, 'Panel'), (2, 'Blog')], default=1),
        ),
        migrations.CreateModel(
            name='LocationBelongToManager',
            fields=[
                ('Code', models.IntegerField(default=index.models.randIntAnything, primary_key=True, serialize=False)),
                ('LocationCode', models.IntegerField()),
                ('RegisterTime', django_jalali.db.models.jDateTimeField(default=index.models.currentDateTime)),
                ('Manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.manager')),
            ],
        ),
    ]
