# Generated by Django 4.2 on 2024-01-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_alter_apikey_foruse_locationbelongtomanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
