# Generated by Django 5.0.1 on 2024-02-04 19:27

import django_jalali.db.models
import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_manager_isdeleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('Code', models.IntegerField(default=index.models.randIntAnything, primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to=index.models.uploadToSlider)),
                ('RegisterTime', django_jalali.db.models.jDateTimeField(default=index.models.currentDateTime)),
            ],
        ),
        migrations.AlterField(
            model_name='village',
            name='Description',
            field=models.TextField(default=' ', max_length=2000),
        ),
    ]
