# Generated by Django 5.0.1 on 2024-02-19 06:31

import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_slider_alter_village_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigcity',
            name='Description',
            field=models.TextField(blank=True, default=' ', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='bigcity',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=index.models.uploadToLocationImage),
        ),
        migrations.AddField(
            model_name='bigvillage',
            name='Description',
            field=models.TextField(blank=True, default=' ', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='bigvillage',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=index.models.uploadToLocationImage),
        ),
        migrations.AddField(
            model_name='city',
            name='Description',
            field=models.TextField(blank=True, default=' ', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=index.models.uploadToLocationImage),
        ),
        migrations.AddField(
            model_name='citypart',
            name='Description',
            field=models.TextField(blank=True, default=' ', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='citypart',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=index.models.uploadToLocationImage),
        ),
        migrations.AddField(
            model_name='village',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=index.models.uploadToLocationImage),
        ),
        migrations.AlterField(
            model_name='village',
            name='Description',
            field=models.TextField(blank=True, default=' ', max_length=2000, null=True),
        ),
    ]
